#SPDX-License-Identifier: MIT-0
---
# tasks file for ensureTargetUserExists
- name: Ensure my user exists
  ansible.builtin.user:
    name: "{{ target_user }}"
    generate_ssh_key: false
    state: present
    update_password: on_create
    groups: "{{ user_groups }}"
    password: "{{ target_password }}"
  become: yes
  become_method: sudo
