---
- name: Setup of the ansible control node
  hosts: control

  tasks:
    - name: run apt or dnf update
      ansible.builtin.package:
        update_cache: yes
        upgrade: yes
      become: yes
      become_method: sudo

    - name: install packages
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: latest
      become: yes
      become_method: sudo

    - name: Ensure the qemu guest agent is running
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
      become: yes
      become_method: sudo

    - name: Clone the control node git repo
      ansible.builtin.git:
        clone: yes
        dest: "{{ repo_base_path }}"
        repo: https://github.com/Sigurdur42/FedoraConfig.git

    - name: Install or update galaxy community modules
      community.general.ansible_galaxy_install:
        dest: "{{ repo_base_path }}/ansibleControlNode/collections/ansible_collections"
        requirements_file: "{{ repo_base_path }}/ansibleControlNode/requirements.yml"
        type: collection

