---
control:
  hosts:
    VM-ANSIBLE-CONTROL:
      # We do not have DNS for this - manual map ip here
      ansible_host: 192.168.178.32
    
    
    # Das ist meine Main Maschine - die machen wir erst später wieder an
    # NB-Papsi-Fedora:   
