---
- name: run DNF update
  become: yes      
  ansible.builtin.dnf:
    use_backend: "{{ dnf_backend }}"
    update_cache: true

- name: Install software packages
  become: yes      
  ansible.builtin.dnf:
    name: "{{ packages_to_install }}"
    state: latest
    use_backend: "{{ dnf_backend }}"
    update_cache: false
