---
clients:
  hosts:
    VM-FEDORA-TEST:
      # We do not have DNS for this - manual map ip here
      ansible_host: 192.168.178.196
    
    # VM-ELEMENTARY-TEST:
    #   # We do not have DNS for this - manual map ip here
    #   ansible_host: 192.168.178.27
    
    # Das ist meine Main Maschine - die machen wir erst später wieder an
    # NB-Papsi-Fedora:   
