---
dnf:
  hosts:
    VM-FEDORA-TEST:
      # We do not have DNS for this - manual map ip here
      ansible_host: 192.168.178.196

apt:
  hosts:
    VM-UBUNTU-TEST:
      # We do not have DNS for this - manual map ip here
      ansible_host: 192.168.178.34

    VM-ELEMENTARY-TEST:
      # We do not have DNS for this - manual map ip here
      ansible_host: 192.168.178.38

clients:
  children:
    dnf:
    apt:  
