---
clients:
  hosts:
    192.168.178.196:
    # Das ist meine Main Maschine - die machen wir erst später wieder an
    # NB-Papsi-Fedora:   
  vars:
    # Eigentlich hätte ich gerne einen separaten ANSIBLE user und nicht root
    ansible_user: root

    # das ist ugly - muss geändert werden
    ansible_password: admin
