---
- name: Setup of my clients
  hosts: clients

  tasks:
    - name: Ensure my user exists
      ansible.builtin.user:
        name: mwagner
        generate_ssh_key: false
        state: present
        update_password: on_create
        groups: "wheel"
        password: $6$WtIUKXlU89ThPBvN$t5MIljRtyYoxAqoFixPPum3oOrA/zm.G0djMA10yKTPXAu8y.AlJAak3ppqV1W1M16Ppb6ziajQh2UQFtU5wV/
      become: yes
      become_method: sudo

    - name: Install software packages
      become: yes      
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: latest        
        update_cache: false      
