---
- name: Setup of my clients
  hosts: clients

  tasks:
    - name: Ensure my user exists
      ansible.builtin.user:
        name: mwagner
        generate_ssh_key: false
        state: present
        update_password: on_create
        groups: "wheel"
        password: $6$WtIUKXlU89ThPBvN$t5MIljRtyYoxAqoFixPPum3oOrA/zm.G0djMA10yKTPXAu8y.AlJAak3ppqV1W1M16Ppb6ziajQh2UQFtU5wV/
      become: yes
      become_method: sudo

    - name: Ensure dnf5 will work on Fedora
      become: yes
      when: ansible_pkg_mgr is match("dnf.*")
      dnf: 
        name: python3-libdnf5
        use_backend: "dnf4"
        state: latest

    - name: Install software packages
      become: yes
      ansible.builtin.package:
        name: "{{ packages_to_install }}"
        state: latest
        update_cache: false

    - name: Create folders for mwagner
      become: yes
      become_user: mwagner
      file:
        name: '{{ item }}'
        state: directory
        recurse: yes
      loop:
        "{{ mwagner_folders }}"

    - name: Check if pCloud already exists
      stat: path=/home/mwagner/pCloud
      register: pcloud_exists

    - name: Download pCloud if not exists
      when: pcloud_exists.stat.exists == False
      get_url:
        dest: /home/mwagner
        url: https://p-lux1.pcloud.com/cBZOomEB3Zd6YO7b7ZZZtHRjXkZ2ZZrD0ZkZ9U8xVZz8ZTzZSYZpRZz4Z1pZnLZdQZpQZEQZGQZyzZU8ZYQZxqNX5Z36hAWHmWicS4se9DVPfhsk1VG23V/pcloud

    - name: Import Microsoft GPG Key
      become: yes
      become_method: sudo
      ansible.builtin.rpm_key:
        key: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code Repo
      become: yes
      become_method: sudo
      ansible.builtin.yum_repository:
        name: vscode
        description: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc
        gpgcheck: true
        enabled: true

    - name: Install VS Code
      become: yes
      become_method: sudo
      ansible.builtin.dnf:
        name: code
        state: present        