---
- name: Setup of my clients
  hosts: clients
  roles:
    - roles/installPackages
    - roles/ensureTargetUserExists
    - roles/nerdfonts
    - roles/vscode
    - roles/ohMyZsh
    - roles/chezmoi

  tasks:
    # - name: Check if pCloud already exists
    #   stat: path=/home/mwagner/pCloud
    #   register: pcloud_exists

    # - name: Download pCloud if not exists
    #   when: pcloud_exists.stat.exists == False
    #   get_url:
    #     dest: /home/mwagner
    #     url: https://p-lux1.pcloud.com/cBZOomEB3Zd6YO7b7ZZZtHRjXkZ2ZZrD0ZkZ9U8xVZz8ZTzZSYZpRZz4Z1pZnLZdQZpQZEQZGQZyzZU8ZYQZxqNX5Z36hAWHmWicS4se9DVPfhsk1VG23V/pcloud
